version: '3'
services:
  database:
    image: "postgres:9.6"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/psql
      POSTGRES_DB: stockplusdb
      POSTGRES_USER: stockplususer
      POSTGRES_PASSWORD: stockpluspass
    ports:
    - 5432:5432
    expose:
    - 5432
volumes:
  db_data:
